name: "Build flakes"
on:
  pull_request:
  push:
jobs:
  winden:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/pqndq1i9g5agiyr5iwwyl061s1c71kl6/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix build "$PWD/systems/winden#darwinConfigurations.winden.system"
